name: Flutter Android Release APK

on: 
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build Android Release APK
        run: flutter build apk --release
        # Note: For a production release, you should configure proper signing
        # in your Android project and securely store signing credentials.
        # Currently, the build.gradle.kts indicates debug signing for release.

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
