name: Flutter Android Release

on:
  workflow_run:
    workflows: ["Flutter Android Build"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.conclusion == 'success' &&
          startsWith(github.event.workflow_run.head_branch, 'refs/tags/') }}

    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release-apk
          path: ./release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.workflow_run.head_branch }}
          name: "Release ${{ github.event.workflow_run.head_branch }}"
          files: ./release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

